<template>
    <StudentTable :students="students" :permissions="permissions" @edit="handleEdit" @delete="handleDelete"
        @view="handleView" />
</template>

<script setup>
definePageMeta({
    layout: 'admin',
})

import StudentTable from '~/components/admin/student/StudentTable.vue'
import { useRouter } from 'vue-router'
import { ref, reactive } from 'vue'

const router = useRouter()

const students = ref([
    {
        id: 1,
        global_id: "STU-G-0001",
        student_code: "STU-001",
        first_name: "Sok",
        last_name: "Dara",
        gender: "male",
        dob: "2002-01-15",
        email: "sok.dara@example.com",
        phone_number: "012345678",
        address: "Phnom Penh, Cambodia",
        profile_image: null,
        generation_id: 1,
        group_id: 1,
        active: 1,
    },
    {
        id: 2,
        global_id: "STU-G-0002",
        student_code: "STU-002",
        first_name: "Chan",
        last_name: "Sreyneang",
        gender: "female",
        dob: "2002-03-20",
        email: "chan.sreyneang@example.com",
        phone_number: "098765432",
        address: "Siem Reap, Cambodia",
        profile_image: null,
        generation_id: 1,
        group_id: 1,
        active: 1,
    },
    {
        id: 3,
        global_id: "STU-G-0003",
        student_code: "STU-003",
        first_name: "Vannak",
        last_name: "Lim",
        gender: "male",
        dob: "2001-11-02",
        email: "vannak.lim@example.com",
        phone_number: "097223344",
        address: "Battambang, Cambodia",
        profile_image: null,
        generation_id: 1,
        group_id: 2,
        active: 1,
    },
    {
        id: 4,
        global_id: "STU-G-0004",
        student_code: "STU-004",
        first_name: "Sreypov",
        last_name: "Kim",
        gender: "female",
        dob: "2002-06-10",
        email: "sreypov.kim@example.com",
        phone_number: "088998877",
        address: "Phnom Penh, Cambodia",
        profile_image: null,
        generation_id: 1,
        group_id: 2,
        active: 1,
    },
    {
        id: 5,
        global_id: "STU-G-0005",
        student_code: "STU-005",
        first_name: "Rith",
        last_name: "Chhay",
        gender: "male",
        dob: "2001-09-25",
        email: "rith.chhay@example.com",
        phone_number: "010112233",
        address: "Koh Kong, Cambodia",
        profile_image: null,
        generation_id: 1,
        group_id: 3,
        active: 1,
    },
    {
        id: 6,
        global_id: "STU-G-0006",
        student_code: "STU-006",
        first_name: "Sokha",
        last_name: "Meas",
        gender: "female",
        dob: "2002-02-05",
        email: "sokha.meas@example.com",
        phone_number: "089667788",
        address: "Kandal, Cambodia",
        profile_image: null,
        generation_id: 2,
        group_id: 3,
        active: 1,
    },
    {
        id: 7,
        global_id: "STU-G-0007",
        student_code: "STU-007",
        first_name: "Borey",
        last_name: "Chea",
        gender: "male",
        dob: "2001-12-14",
        email: "borey.chea@example.com",
        phone_number: "096554433",
        address: "Takeo, Cambodia",
        profile_image: null,
        generation_id: 2,
        group_id: 1,
        active: 0,
    },
    {
        id: 8,
        global_id: "STU-G-0008",
        student_code: "STU-008",
        first_name: "Lina",
        last_name: "Heng",
        gender: "female",
        dob: "2002-04-18",
        email: "lina.heng@example.com",
        phone_number: "097665544",
        address: "Kampot, Cambodia",
        profile_image: null,
        generation_id: 2,
        group_id: 2,
        active: 1,
    },
    {
        id: 9,
        global_id: "STU-G-0009",
        student_code: "STU-009",
        first_name: "Phirun",
        last_name: "Sann",
        gender: "male",
        dob: "2001-08-09",
        email: "phirun.sann@example.com",
        phone_number: "093112233",
        address: "Prey Veng, Cambodia",
        profile_image: null,
        generation_id: 2,
        group_id: 2,
        active: 1,
    },
    {
        id: 10,
        global_id: "STU-G-0010",
        student_code: "STU-010",
        first_name: "Sreymao",
        last_name: "Long",
        gender: "female",
        dob: "2002-07-01",
        email: "sreymao.long@example.com",
        phone_number: "097334455",
        address: "Svay Rieng, Cambodia",
        profile_image: null,
        generation_id: 2,
        group_id: 3,
        active: 1,
    },
    {
        id: 11,
        global_id: "STU-G-0011",
        student_code: "STU-011",
        first_name: "Dara",
        last_name: "Suon",

        gender: "male",
        dob: "2001-10-11",
        email: "dara.suon@example.com",
        phone_number: "092776655",
        address: "Phnom Penh, Cambodia",
        profile_image: null,
        generation_id: 3,
        group_id: 1,
        active: 0,
    },
    {
        id: 12,
        global_id: "STU-G-0012",
        student_code: "STU-012",
        first_name: "Sreynich",
        last_name: "Ros",
        gender: "female",
        dob: "2002-05-21",
        email: "sreynich.ros@example.com",
        phone_number: "096223344",
        address: "Kampong Cham, Cambodia",
        profile_image: null,
        generation_id: 3,
        group_id: 1,
        active: 1,
    },
    {
        id: 13,
        global_id: "STU-G-0013",
        student_code: "STU-013",
        first_name: "Vuthy",
        last_name: "Im",
        gender: "male",
        dob: "2001-03-03",
        email: "vuthy.im@example.com",
        phone_number: "088335577",
        address: "Kampong Chhnang, Cambodia",
        profile_image: null,
        generation_id: 3,
        group_id: 2,
        active: 1,
    },
    {
        id: 14,
        global_id: "STU-G-0014",
        student_code: "STU-014",
        first_name: "Srey mom",
        last_name: "Kong",
        gender: "female",
        dob: "2002-09-30",
        email: "sreymom.kong@example.com",
        phone_number: "099887700",
        address: "Kampong Speu, Cambodia",
        profile_image: null,
        generation_id: 3,
        group_id: 3,
        active: 1,
    },
    {
        id: 15,
        global_id: "STU-G-0015",
        student_code: "STU-015",
        first_name: "Rithy",
        last_name: "Ouk",
        gender: "male",
        dob: "2001-06-06",
        email: "rithy.ouk@example.com",
        phone_number: "096443322",
        address: "Koh Kong, Cambodia",
        profile_image: null,
        generation_id: 3,
        group_id: 3,
        active: 0,
    },
    {
        id: 16,
        global_id: "STU-G-0016",
        student_code: "STU-016",
        first_name: "Sophea",
        last_name: "Keo",
        gender: "female",
        dob: "2002-01-28",
        email: "sophea.keo@example.com",
        phone_number: "089667799",
        address: "Banteay Meanchey, Cambodia",
        profile_image: null,
        generation_id: 4,
        group_id: 1,
        active: 1,
    },
    {
        id: 17,
        global_id: "STU-G-0017",
        student_code: "STU-017",
        first_name: "Chenda",
        last_name: "Ek",
        gender: "female",
        dob: "2002-04-04",
        email: "chenda.ek@example.com",
        phone_number: "090556677",
        address: "Pursat, Cambodia",
        profile_image: null,
        generation_id: 4,
        group_id: 2,
        active: 1,
    },
    {
        id: 18,
        global_id: "STU-G-0018",
        student_code: "STU-018",
        first_name: "Virak",
        last_name: "Phan",
        gender: "male",
        dob: "2001-05-17",
        email: "virak.phan@example.com",
        phone_number: "087778899",
        address: "Kampong Thom, Cambodia",
        profile_image: null,
        generation_id: 4,
        group_id: 2,
        active: 1,
    },
    {
        id: 19,
        global_id: "STU-G-0019",
        student_code: "STU-019",
        first_name: "Srey leak",
        last_name: "Tea",
        gender: "female",
        dob: "2002-02-08",
        email: "sreyleak.tea@example.com",
        phone_number: "093556677",
        address: "Ratanakiri, Cambodia",
        profile_image: null,
        generation_id: 4,
        group_id: 3,
        active: 0,
    },
    {
        id: 20,
        global_id: "STU-G-0020",
        student_code: "STU-020",
        first_name: "Sarin",
        last_name: "Kun",
        gender: "male",
        dob: "2001-01-01",
        email: "sarin.kun@example.com",
        phone_number: "010889900",
        address: "Mondulkiri, Cambodia",
        profile_image: null,
        generation_id: 4,
        group_id: 3,
        active: 1,
    },
]);

const permissions = reactive({
    add: true,
    edit: true,
    delete: true,
    list: true,
})

const handleEdit = (id) => router.push(`/admin/student/edit/${id}`)
const handleDelete = (id) => {
    students.value = students.value.filter(s => s.id !== id)
}
const handleView = () => { }
</script>


<style scoped>
.layout-body {
    flex-grow: 1;
}

/* Consistent spacing with other admin pages */
.student-page-container {
    padding: 20px 24px;
    margin: 0;
    max-width: none;
}
</style>
